In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
dataset=pd.read_csv('Magic.csv')

In [4]:
dataset

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0
...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0

In [5]:
dataset.head()

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,6500000,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,5000000,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,15500000,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,4200000,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,6200000,Ready_to_move,New_Property,Builder_Floor,6667.0

In [6]:
dataset.tail()

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Price,Status,Transaction,Type,Per_Sqft
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,55000000,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,12500000,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,17500000,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,11500000,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,18500000,Ready_to_move,New_Property,Builder_Floor,12916.0

In [7]:
dataset.columns

Index(['Area', 'BHK', 'Bathroom', 'Furnishing', 'Locality', 'Parking', 'Price',
       'Status', 'Transaction', 'Type', 'Per_Sqft'],
      dtype='object')

In [8]:
dataset.columns.size

11

In [9]:
x=dataset.drop(["Price"],axis=1)
x

,Area,BHK,Bathroom,Furnishing,Locality,Parking,Status,Transaction,Type,Per_Sqft
0,800.0,3,2.0,Semi-Furnished,Rohini Sector 25,1.0,Ready_to_move,New_Property,Builder_Floor,NaN
1,750.0,2,2.0,Semi-Furnished,"J R Designers Floors, Rohini Sector 24",1.0,Ready_to_move,New_Property,Apartment,6667.0
2,950.0,2,2.0,Furnished,"Citizen Apartment, Rohini Sector 13",1.0,Ready_to_move,Resale,Apartment,6667.0
3,600.0,2,2.0,Semi-Furnished,Rohini Sector 24,1.0,Ready_to_move,Resale,Builder_Floor,6667.0
4,650.0,2,2.0,Semi-Furnished,Rohini Sector 24 carpet area 650 sqft status R...,1.0,Ready_to_move,New_Property,Builder_Floor,6667.0
...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,Unfurnished,Chittaranjan Park,3.0,Ready_to_move,New_Property,Builder_Floor,12916.0
1255,1050.0,3,2.0,Semi-Furnished,Chittaranjan Park,3.0,Ready_to_move,Resale,Builder_Floor,12916.0
1256,875.0,3,3.0,Semi-Furnished,Chittaranjan Park,3.0,Ready_to_move,New_Property,Builder_Floor,12916.0
1257,990.0,2,2.0,Unfurnished,Chittaranjan Park Block A,1.0,Ready_to_move,Resale,Builder_Floor,12916.0
1258,11050.0,3,3.0,Unfurnished,Chittaranjan Park,1.0,Ready_to_move,New_Property,Builder_Floor,12916.0

In [10]:
y=dataset["Price"]
y

0        6500000
1        5000000
2       15500000
3        4200000
4        6200000
          ...
1254    55000000
1255    12500000
1256    17500000
1257    11500000
1258    18500000
Name: Price, Length: 1259, dtype: int64

In [11]:
y.size

1259

In [12]:
dataset.columns

Index(['Area', 'BHK', 'Bathroom', 'Furnishing', 'Locality', 'Parking', 'Price',
       'Status', 'Transaction', 'Type', 'Per_Sqft'],
      dtype='object')

In [13]:
print(dataset['Furnishing'].unique())

['Semi-Furnished' 'Furnished' 'Unfurnished' nan]

In [14]:
print(dataset['Status'].unique())

['Ready_to_move' 'Almost_ready']

In [15]:
print(dataset['Transaction'].unique())

['New_Property' 'Resale']

In [16]:
print(dataset['Type'].unique())

['Builder_Floor' 'Apartment' nan]

In [17]:
print(x.columns[x.isna().any()])

Index(['Bathroom', 'Furnishing', 'Parking', 'Type', 'Per_Sqft'], dtype='object')

In [18]:
x["Per_Sqft"].isna().any()

np.True_

In [19]:
x.Per_Sqft=x.Per_Sqft.fillna(x.Per_Sqft.mean())

In [20]:
x["Parking"].isna().any()

np.True_

In [21]:
x.Parking=x.Parking.fillna(x.Parking.mean())

In [22]:
x["Bathroom"].isna().any()

np.True_

In [23]:
x["Bathroom"] = x["Bathroom"].fillna(x["Bathroom"].mean())

In [24]:
x["Furnishing"] = x["Furnishing"].fillna("Semi-Furnished")

In [25]:
x["Furnishing"]=x["Furnishing"].map({"Unfurnished":0,"Semi-Furnished":1,"Furnished":2,"nan":3})

In [26]:
print(dataset["Status"].isna().sum())

0

In [27]:
x['Status']=x['Status'].map({'Ready to move':0,'Almost ready':1})

In [28]:
x['Transaction']=x['Transaction'].map({'New':0,'Resale':1})

In [29]:
x['Type']=x['Type'].map({'Builder_Floor':0, 'Apartment':1,'nan':2})

In [30]:
x=pd.get_dummies(x,columns=['Locality'],drop_first=True)

In [31]:
print(dataset.columns)

Index(['Area', 'BHK', 'Bathroom', 'Furnishing', 'Locality', 'Parking', 'Price',
       'Status', 'Transaction', 'Type', 'Per_Sqft'],
      dtype='object')

In [32]:
print(y.isna().any())

False

In [33]:
print(x.isnull().sum())

Area                                                                                                                                                                                                                                                                                                                                               0
BHK                                                                                                                                                                                                                                                                                                                                                0
Bathroom                                                                                                                                                                                                                                                                                                                                           0
Furnishing                                                                                                                                                                                                                                                                                                                                         0
Parking                                                                                                                                                                                                                                                                                                                                            0
                                                                                                                                                                                                                                                                                                                                                  ..
Locality_Vishwas Nagar, Shahdara                                                                                                                                                                                                                                                                                                                   0
Locality_Yamuna Apartment, Alaknanda                                                                                                                                                                                                                                                                                                               0
Locality_Yamuna Vihar, Shahdara                                                                                                                                                                                                                                                                                                                    0
Locality_Zakir Nagar, New Friends Colony                                                                                                                                                                                                                                                                                                           0
Locality_mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar    0
Length: 373, dtype: int64

In [34]:
x = x.fillna(0)

In [35]:
x

,Area,BHK,Bathroom,Furnishing,Parking,Status,Transaction,Type,Per_Sqft,"Locality_Aashirwaad Chowk, Dwarka",...,"Locality_Vijay Enclave, Mahavir Enclave","Locality_Vijay Vihar, Rohini","Locality_Vikram Vihar, Lajpat Nagar","Locality_Vinoba Puri, Lajpat Nagar","Locality_Virat Residency, Dwarka Mor","Locality_Vishwas Nagar, Shahdara","Locality_Yamuna Apartment, Alaknanda","Locality_Yamuna Vihar, Shahdara","Locality_Zakir Nagar, New Friends Colony","Locality_mind. The space is airy, is well located and can be easily customized as per the needs. Prime facilities are easily accessible from this place with Government Girls Senior Secondary School No 2 (0 km ). Other key neighbourhood are B Block Market (0 km ). read more Contact Owner View Phone No. Share Feedback Owner vinod kumar"
0,800.0,3,2.0,1,1.0,0.0,0.0,0.0,15690.136542,False,...,False,False,False,False,False,False,False,False,False,False
1,750.0,2,2.0,1,1.0,0.0,0.0,1.0,6667.000000,False,...,False,False,False,False,False,False,False,False,False,False
2,950.0,2,2.0,2,1.0,0.0,1.0,1.0,6667.000000,False,...,False,False,False,False,False,False,False,False,False,False
3,600.0,2,2.0,1,1.0,0.0,1.0,0.0,6667.000000,False,...,False,False,False,False,False,False,False,False,False,False
4,650.0,2,2.0,1,1.0,0.0,0.0,0.0,6667.000000,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,4118.0,4,5.0,0,3.0,0.0,0.0,0.0,12916.000000,False,...,False,False,False,False,False,False,False,False,False,False
1255,1050.0,3,2.0,1,3.0,0.0,1.0,0.0,12916.000000,False,...,False,False,False,False,False,False,False,False,False,False
1256,875.0,3,3.0,1,3.0,0.0,0.0,0.0,12916.000000,False,...,False,False,False,False,False,False,False,False,False,False
1257,990.0,2,2.0,0,1.0,0.0,1.0,0.0,12916.000000,False,...,False,False,False,False,False,False,False,False,False,False
1258,11050.0,3,3.0,0,1.0,0.0,0.0,0.0,12916.000000,False,...,False,False,False,False,False,False,False,False,False,False

In [36]:
from sklearn.model_selection import train_test_split

(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.25,random_state=0)

In [37]:
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()


x_train = scaler.fit_transform(x_train)
x_test  = scaler.transform(x_test)

In [38]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [39]:
y_pred = model.predict(x_test)

In [40]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
print(mse)

299023866552024.9

In [43]:
from sklearn.metrics import r2_score
y_pred = model.predict(x_test)
print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.37750290191627134

In [45]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(rmse)

17292306.571190115

In [46]:
print("R2 Score:", r2_score(y_test, y_pred))
print("MSE     :", mean_squared_error(y_test, y_pred))
print("RMSE    :", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.37750290191627134
MSE     : 299023866552024.9
RMSE    : 17292306.571190115